### ISSUE TITLE
Unity project for generating new images

### ISSUE THREAD

**Issue by jpsml** [hou-yz/MultiviewX#5]
Are you able to share the Unity project that you used for generating the dataset images? This would be great, since it would allow the creation of new datasets.

**Comment by luorix1** [comment]
Hello, I would also appreciate it if you could share the Unity project you used for generating the dataset. As @jpsml stated, it would be a huge help in creating new datasets. Thank you very much.

**Comment by hou-yz** [comment]
Hi guys,
Thank you for your interest. But sorry, I believe that there are some assets we purchased for this project that have IP issues and prevent us from releasing the Unity project itself. I'll let you know if there are any updates.
Best,
Yunzhong
