### ISSUE TITLE
Regarding Unity

### ISSUE THREAD

**Issue by luorix1** [hou-yz/MultiviewX#6]
Hello, I am a researcher trying to create a varying synthetic dataset for testing purposes (similar in nature to MultiviewX) based on the PersonX repo.
However, I am new to Unity and conventional info doesn't seem to be of much help. I was hoping that you could perhaps provide me with some pointers on controlling multiple "Game object"s. When I just created multiple people by adding a for loop to the PersonX repo example code, only one seemed to move while the others stayed in one place.
I understand from the other issues that you cannot publish the inner workings of MultiviewX but any help you could give on the subject would be extremely helpful. Thank you.

**Comment by hou-yz** [comment]
Thank you for your interest.
However, that seems some coding error and I cannot help you with that. What we did in MultiviewX is create walking paths for the pedestrian and then populate them with prefabs from PersonX.
Hope this helps.
Yunzhong
